replicaCount: 1

image:
  repository: ghcr.io/jelleby/podwatch_operator
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  nodePort: 30000

env:
  FLASK_ENV: development

serviceAccount:
  create: true
  name: ""
