apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podwatch-operator.fullname" . }}
  labels:
    {{- include "podwatch-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "podwatch-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "podwatch-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "podwatch-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: FLASK_ENV
              value: {{ .Values.env.FLASK_ENV | quote }}
